# Generated by Django 4.1.1 on 2022-10-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StatLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('player', models.CharField(max_length=255)),
                ('min', models.FloatField()),
                ('made_2', models.IntegerField()),
                ('attempts_2', models.IntegerField()),
                ('made_3', models.IntegerField()),
                ('attempts_3', models.IntegerField()),
                ('made_ft', models.IntegerField()),
                ('attempts_ft', models.IntegerField()),
                ('reb_o', models.IntegerField()),
                ('reb_d', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('poa', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('fd', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.match')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
