# Generated by Django 4.1.1 on 2022-10-10 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playergamestats',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='date_now',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 18, 44, 29, 988940)),
        ),
    ]
