# Generated by Django 4.1.1 on 2022-10-10 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_playergamestats_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamestats',
            name='date_now',
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='time_now',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 18, 45, 19, 869233)),
        ),
    ]
