# Generated by Django 4.1.1 on 2022-10-10 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_playergamestats_date_now_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_now', models.DateTimeField(default=datetime.datetime(2022, 10, 10, 19, 45, 19, 214648))),
                ('date', models.DateTimeField()),
                ('player', models.CharField(max_length=255)),
                ('min', models.FloatField()),
                ('made_2', models.IntegerField()),
                ('attempts_2', models.IntegerField()),
                ('made_3', models.IntegerField()),
                ('attempts_3', models.IntegerField()),
                ('made_ft', models.IntegerField()),
                ('attempts_ft', models.IntegerField()),
                ('reb_o', models.IntegerField()),
                ('reb_d', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('poa', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('fd', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('blocks', models.IntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='PlayerGameStats',
        ),
    ]
