# Generated by Django 4.1.1 on 2022-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_upload_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('player', models.CharField(max_length=255)),
                ('min', models.FloatField()),
                ('made_2', models.IntegerField()),
                ('attempts_2', models.IntegerField()),
                ('made_3', models.IntegerField()),
                ('attempts_3', models.IntegerField()),
                ('made_ft', models.IntegerField()),
                ('attempts_ft', models.IntegerField()),
                ('reb_o', models.IntegerField()),
                ('reb_d', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('poa', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('fd', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('blocks', models.IntegerField()),
            ],
        ),
    ]
