# Generated by Django 4.1.1 on 2022-10-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_playergamestat_delete_playergamestats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamestat',
            name='time_now',
        ),
    ]
