# Generated by Django 4.1.1 on 2022-10-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_playergamestat_time_now'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerGameStat',
            new_name='Stat',
        ),
    ]
